import './style.css';
import './history.css';
import {D,currentBalances,generatorAllocation,generatorSettlement} from './ledger.js';
let history,state,page='overview',periodId='',house=1,sheet='Financials',search='';
const app=document.querySelector('#app');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>x==null?'—':new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',minimumFractionDigits:2,maximumFractionDigits:2}).format(D(x).toNumber());
const mf=f=>f?.type==='n'&&f.value!=null?money(f.value):esc(f?.value??'—');
const p=()=>history.periods.find(p=>p.id===periodId);
const src=(ref,label='Source')=>`<button class="text-button" data-source="${esc(ref)}">${esc(label)}</button>`;
const balance=b=>`<strong>${money(D(b).abs())}</strong><span class="badge ${D(b).gt(0)?'good':D(b).toDecimalPlaces(2).eq(0)?'neutral':'danger'}">${D(b).toDecimalPlaces(2).eq(0)?'Settled':D(b).gt(0)?'Credit':'Due'}</span>`;
async function api(path,body){const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load records.');return data;}
async function load(){try{[history,state]=await Promise.all([api('history'),api('state')]);periodId ||=history.periods.at(-1).id;render();}catch(e){app.innerHTML=`<main><h1>Estate records unavailable</h1><p>${esc(e.message)}</p><button id="retry">Retry</button></main>`;document.querySelector('#retry').onclick=load;}}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">No records in this view.</td></tr>`}</tbody></table></div>`;}
function picker(){return `<label class="picker">Billing period<select id="period">${history.periods.map(x=>`<option value="${x.id}" ${periodId===x.id?'selected':''}>${x.label}</option>`).join('')}</select></label>`;}
function metrics(items){return `<section class="metrics">${items.map(([label,value,note])=>`<article class="metric"><p>${label}</p><strong>${value}</strong><small>${note||''}</small></article>`).join('')}</section>`;}
function overview(){const rows=history.statements.filter(s=>s.period===periodId),dues=rows.reduce((s,r)=>s.plus(D(r.closing).lt(0)?D(r.closing).neg():0),D(0)),credits=rows.reduce((s,r)=>s.plus(D(r.closing).gt(0)?r.closing:0),D(0));return `${picker()}${metrics([['Estate service bills',mf(p().billTotal),src(p().billTotalSource)],['Participating houses',p().occupied.length,'Recorded participation for this period'],['House balances due',money(dues),'Source closing balances'],['House credits',money(credits),'Shown separately from amounts due']])}<article class="panel"><h2>${esc(p().label)} · all houses</h2>${table(['House','Service charge','Diesel','Power','Generator','Credit / opening','Paid','Closing balance'],rows.map(s=>`<tr><td><button class="text-button" data-house="${s.house}">House ${s.house}</button><small>${s.occupancy==='unoccupied'?'Unoccupied':''}</small></td>${['Service Charge','Diesel','Power','Generator','Credit','Paid'].map(k=>`<td>${mf(s.fields[k])}</td>`).join('')}<td>${balance(s.closing)}${src(s.fields.Outstanding.source)}</td></tr>`))}</article>${metrics([['New ledger records',state.entries.length,'Recorded after the source import'],['Complete archive',history.sheets.length+' sheets',history.statements.length+' monthly house statements'],['Source imported',new Date(history.importedAt).toLocaleDateString('en-GB'),'Snapshot of the live workbook']])}`;}
function accounts(){const rows=history.statements.filter(s=>s.house===house),current=currentBalances(history,state.entries).find(s=>s.house===house);return `<div class="page-toolbar"><label class="picker">House<select id="house">${Array.from({length:9},(_,i)=>`<option value="${i+1}" ${house===i+1?'selected':''}>House ${i+1}</option>`).join('')}</select></label><div>${balance(current.balance)}<small>Current balance including new records</small></div></div><article class="panel"><h2>House ${house} · complete monthly history</h2><p>Positive balances are credits. Negative balances are amounts due. Original figures and written statuses are preserved.</p>${table(['Period','Service','Diesel','Power','Generator','Credit / opening','Paid','Closing','Recorded status'],rows.map(s=>`<tr><td>${history.periods.find(p=>p.id===s.period).label}${src(s.fields.Outstanding.source)}</td>${['Service Charge','Diesel','Power','Generator','Credit','Paid'].map(k=>`<td>${mf(s.fields[k])}</td>`).join('')}<td>${money(s.closing)}</td><td>${esc(s.fields.Status.value||'—')}</td></tr>`))}</article><article class="panel spaced"><h2>Credit adjustments in the workbook</h2>${table(['Period','Credit relative to previous closing','Original formula / value'],rows.filter(s=>D(s.carryAdjustment).abs().gt('0.01')).map(s=>`<tr><td>${esc(s.period)}</td><td>${money(s.carryAdjustment)}</td><td><code>${esc(s.fields.Credit.formula||s.fields.Credit.value)}</code>${src(s.fields.Credit.source)}</td></tr>`))}</article><article class="panel spaced"><h2>New records for House ${house}</h2>${entryTable(state.entries.filter(e=>e.house===house||e.allocations?.some(a=>a.house===house)))}</article>`;}
function bills(){return `${picker()}${metrics([['Source bill total',mf(p().billTotal),src(p().billTotalSource)],['Participating houses',p().occupied.length,'Excluded: '+(Array.from({length:9},(_,i)=>i+1).filter(h=>!p().occupied.includes(h)).join(', ')||'none')]])}<article class="panel"><h2>${p().label} · original bills</h2><p>Blank payments and pending amounts stay as recorded. Written statuses are retained even where the amount-paid cell is empty.</p>${table(['Item','Category','Vendor','Billed','Paid','Outstanding','Written status','Source'],history.bills.filter(b=>b.period===periodId).map(b=>`<tr><td>${esc(b.fields.item.value)}</td><td>${esc(b.fields.category.value)}</td><td>${esc(b.fields.vendor.value||'—')}</td><td>${mf(b.fields.billed)}</td><td>${mf(b.fields.paid)}</td><td>${mf(b.fields.outstanding)}</td><td>${esc(b.fields.status.value||'—')}</td><td>${src(b.fields.billed.source)}</td></tr>`))}</article>`;}
function bank(){const rows=history.bank.filter(b=>JSON.stringify(b).toLowerCase().includes(search.toLowerCase()));return `<div class="page-toolbar"><h2>All ${history.bank.length} bank entries</h2><label class="picker">Search<input id="search" value="${esc(search)}" placeholder="Description, date or amount"></label></div><p>Bank cash movement is separate from house payment allocations, so the same receipt is not credited twice.</p><article class="panel">${table(['Date as imported','Description','Signed amount','Source'],rows.map(b=>`<tr><td>${esc(b.date?.replace('T',' ')||'—')}</td><td>${esc(b.fields.description.value)}</td><td>${mf(b.fields.amount)}</td><td>${src(b.fields.amount.source)}</td></tr>`))}</article>`;}
function venco(){return `<h2>${history.venco.length} original Venco records</h2><p>Original transaction dates, credited units, and amounts are preserved.</p><article class="panel">${table(['Date','Unit label','Units','Amount','Source'],history.venco.map(v=>`<tr><td>${esc(v.date?.replace('T',' ')||'—')}</td><td>${esc(v.unit)}</td><td>${esc(v.units?.value??'—')}</td><td>${mf(v.amount)}</td><td>${src(v.source.split(':')[0])}</td></tr>`))}</article>`;}
function archive(){const cells=history.sheets.find(s=>s.name===sheet).cells,rows=Object.entries(cells).filter(([a,c])=>(a+' '+c.value+' '+c.formula).toLowerCase().includes(search.toLowerCase()));return `<div class="page-toolbar"><label class="picker">Original sheet<select id="sheet">${history.sheets.map(s=>`<option ${s.name===sheet?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label class="picker">Find cell, value or formula<input id="search" value="${esc(search)}"></label></div><p>${Object.keys(cells).length} populated cells. Original precision and formulas are preserved. <a href="/api/original" download="Alexandria-original.xlsx">Download original workbook</a></p><article class="panel">${table(['Cell','Value as stored','Original formula'],rows.map(([a,c])=>`<tr><td>${esc(a)}</td><td>${esc(c.value??'(blank)')}</td><td><code>${esc(c.formula||'')}</code></td></tr>`))}</article>`;}
function entryTable(entries){return table(['Date','Type','House / allocation','Amount','Description / reference','Recorder'],entries.map(e=>`<tr><td>${esc(e.date)}<small>${esc(e.createdAt)}</small></td><td>${esc(e.kind)}</td><td>${e.house?'House '+e.house:e.allocations?.map(a=>'H'+a.house+': '+money(a.amount)).join('<br>')||'Generator fund'}</td><td>${money(e.amount)}</td><td>${esc(e.note)}<small>${esc(e.reference||'')}</small></td><td>${esc(e.actor)}</td></tr>`));}
function records(){return `<div class="page-toolbar"><h2>Records since the import</h2>${state.recorder?'<button class="primary" id="new-record">Record transaction</button>':''}<a href="/api/backup" download="alexandria-backup.json">Download complete backup</a></div><article class="panel">${entryTable(state.entries)}</article>${state.owner?`<article class="panel spaced"><h2>Designated committee recorders</h2><p>${esc(state.email)} is the owner. Only the owner and designated recorders may enter transactions.</p><form id="recorder-form"><label>Email<input type="email" name="email" required></label><button class="primary">Add recorder</button></form>${table(['Recorder email','Added'],state.recorders.map(r=>`<tr><td>${esc(r.email)}</td><td>${esc(r.created_at)}</td></tr>`))}</article>`:''}`;}
function generator(){const expenses=state.entries.filter(e=>e.kind==='generator-expense').reduce((s,e)=>s.plus(e.amount),D(0)),received=state.entries.filter(e=>e.kind==='payment'&&e.fund==='generator').reduce((s,e)=>s.plus(e.amount),D(0));return `${metrics([['Generator receipts',money(received),'Payments explicitly allocated to this fund'],['Actual generator spending',money(expenses),'Diesel, servicing and operating costs'],['Fund cash movement',money(received.minus(expenses)),'Since import; opening fund cash not supplied']])}<article class="panel"><h2>Generator contribution calculator</h2>${state.recorder?'<button id="settle-generator" class="secondary">Reconcile a recorded advance</button>':''}<p>Enter the approved budget and credited or estimated units. The proposed availability share is 20–30%; the rest follows units. Historical charges stay unchanged.</p><form id="generator-form"><div class="form-grid"><label>Generator budget (₦)<input name="budget" type="number" min="0.01" step="0.01" required></label><label>Availability share (%)<input name="rate" type="number" value="25" min="20" max="30" required></label><label>Billing date<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Unmetered estimation basis<select name="basis"><option>Average of occupied metered houses</option><option>Approved historical estimate</option></select></label></div><p>Houses 1, 5 and 9 are unmetered in the source. Tick occupied houses and enter credited or estimated units.</p>${table(['House','Occupied for this period','Units (kWh)','Basis'],Array.from({length:9},(_,i)=>i+1).map(h=>`<tr><td>House ${h}</td><td><input aria-label="House ${h} occupied" type="checkbox" name="occupied" value="${h}" ${history.periods.at(-1).occupied.includes(h)?'checked':''}></td><td><input aria-label="House ${h} units" type="number" step="0.0001" min="0" name="units${h}"></td><td>${[1,5,9].includes(h)?'Estimated':'Prepaid credited units'}</td></tr>`))}<button type="button" id="estimate" class="secondary">Fill unmetered units from metered average</button> <button class="primary">Calculate contribution</button><div id="generator-result" aria-live="polite"></div></form></article>`;}
function render(){const titles={overview:'Estate balances',accounts:'House statements',bills:'Monthly bills',bank:'Bank history',venco:'Venco history',archive:'Original workbook',records:'Recorder & audit trail',generator:'Generator fund'};app.innerHTML=`<div class="app-shell"><aside><div class="brand"><span class="brand-mark">A</span><div><strong>Alexandria</strong><small>Terrace I</small></div></div><nav>${Object.entries(titles).map(([key,t])=>`<button class="nav-item ${page===key?'active':''}" data-page="${key}">${t}</button>`).join('')}</nav><div class="aside-bottom"><small>${state.local?'Local preview':'Shared estate records'}</small><p>${esc(state.email)}</p></div></aside><main><header><div><p class="eyebrow">${state.recorder?'Authorised recorder':'Resident · read access'}</p><h1>${titles[page]}</h1></div><button id="refresh" class="secondary">Refresh</button></header><div id="message" role="status"></div>${state.owner&&!state.imported?'<p>The source snapshot is available. <button id="initialise-archive" class="primary">Save original archive to shared database</button></p>':''}${({overview,accounts,bills,bank,venco,archive,records,generator})[page]()}</main></div><dialog id="dialog"></dialog>`;bind();}
function report(message){document.querySelector('#message').textContent=message;}
function showSource(ref){const [name,address]=ref.split('!'),c=history.sheets.find(s=>s.name===name)?.cells[address],dialog=document.querySelector('#dialog');dialog.innerHTML=`<button id="close" class="secondary">Close</button><h2>${esc(ref)}</h2><p>Stored value: <strong>${esc(c?.value??'(blank)')}</strong></p><p>Formula: <code>${esc(c?.formula||'Directly entered value')}</code></p><a href="${history.sourceUrl}" target="_blank" rel="noopener">Open original workbook</a>`;dialog.showModal();document.querySelector('#close').onclick=()=>dialog.close();}
function transactionForm(){const recordKey=crypto.randomUUID(),dialog=document.querySelector('#dialog');dialog.innerHTML=`<button class="secondary" id="close">Close</button><h2>Record a transaction</h2><p>Corrections are separate debits or credits with a reason. The source history is preserved.</p><form id="transaction-form"><label>Type<select name="kind" id="kind"><option value="payment">House payment received</option><option value="bill">New shared estate bill</option><option value="adjustment">House balance correction</option><option value="generator-expense">Generator expense paid</option></select></label><label>Date<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Amount (₦)<input type="number" name="amount" min="0.01" step="0.01" required></label><label>Description / reason<textarea name="note" required maxlength="500"></textarea></label><div id="type-fields"></div><p class="error" id="form-error" role="alert"></p><button class="primary">Save record</button></form>`;dialog.showModal();document.querySelector('#close').onclick=()=>dialog.close();document.querySelector('#kind').onchange=transactionFields;transactionFields();document.querySelector('#transaction-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),raw=Object.fromEntries(f);raw.id=recordKey;raw.house=+raw.house;raw.houses=f.getAll('houses').map(Number);e.submitter.disabled=true;try{await api('entries',raw);dialog.close();await load();report('Record saved.');}catch(error){document.querySelector('#form-error').textContent=error.message;e.submitter.disabled=false;}};}
function transactionFields(){const type=document.querySelector('#kind').value;document.querySelector('#type-fields').innerHTML=(type==='payment'||type==='adjustment'?`<label>House<select name="house">${Array.from({length:9},(_,i)=>`<option value="${i+1}">House ${i+1}</option>`).join('')}</select></label>`:'')+(type==='payment'?'<label>Bank / receipt reference<input name="reference" required maxlength="120"></label><label>Fund<select name="fund"><option value="general">General estate account</option><option value="generator">Generator advance contribution</option></select></label>':type==='adjustment'?'<label>Direction<select name="direction"><option value="credit">Credit — reduces amount due</option><option value="debit">Debit — increases amount due</option></select></label>':type==='bill'?`<label>Category<select name="category">${['Cleaning','Water','Security','Waste','Repairs','Other'].map(c=>`<option>${c}</option>`).join('')}</select></label><fieldset><legend>Houses sharing this bill</legend>${Array.from({length:9},(_,i)=>i+1).map(h=>`<label class="check"><input name="houses" type="checkbox" value="${h}" ${history.periods.at(-1).occupied.includes(h)?'checked':''}>House ${h}</label>`).join('')}</fieldset>`:'<p>Generator spending reduces the fund cash. It does not charge residents a second time.</p>');}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;search='';render();});document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>{house=+b.dataset.house;page='accounts';render();});document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>showSource(b.dataset.source));document.querySelector('#refresh').onclick=load;document.querySelector('#period')?.addEventListener('change',e=>{periodId=e.target.value;render();});document.querySelector('#house')?.addEventListener('change',e=>{house=+e.target.value;render();});document.querySelector('#sheet')?.addEventListener('change',e=>{sheet=e.target.value;search='';render();});document.querySelector('#search')?.addEventListener('change',e=>{search=e.target.value;render();});document.querySelector('#new-record')?.addEventListener('click',transactionForm);document.querySelector('#recorder-form')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('recorders',Object.fromEntries(new FormData(e.target)));await load();report('Recorder added.');}catch(error){report(error.message);}});document.querySelector('#settle-generator')?.addEventListener('click',settlementForm);document.querySelector('#initialise-archive')?.addEventListener('click',async e=>{e.target.disabled=true;try{await api('import',{});await load();report('Original archive saved to the shared database.');}catch(error){report(error.message);e.target.disabled=false;}});bindGenerator();}
function generatorInputs(form){const f=new FormData(form);return{budget:f.get('budget'),rate:+f.get('rate'),occupied:f.getAll('occupied').map(Number),units:Object.fromEntries(Array.from({length:9},(_,i)=>[i+1,f.get('units'+(i+1))])),date:f.get('date'),basis:f.get('basis')};}
function bindGenerator(){const form=document.querySelector('#generator-form');if(!form)return;document.querySelector('#estimate').onclick=()=>{try{const input=generatorInputs(form),metered=input.occupied.filter(h=>![1,5,9].includes(h));if(!metered.length||metered.some(h=>!input.units[h]))throw Error('Enter credited units for all occupied metered houses first.');const average=metered.reduce((s,h)=>s.plus(input.units[h]),D(0)).div(metered.length).toFixed(4);input.occupied.filter(h=>[1,5,9].includes(h)).forEach(h=>form.elements['units'+h].value=average);}catch(e){report(e.message);}};form.onsubmit=e=>{e.preventDefault();try{const input=generatorInputs(form),rows=generatorAllocation(input),result=document.querySelector('#generator-result'),id=crypto.randomUUID();result.innerHTML=table(['House','Availability','Consumption','Total'],rows.map(r=>`<tr><td>House ${r.house}</td><td>${money(r.availability)}</td><td>${money(r.consumption)}</td><td>${money(r.amount)}</td></tr>`))+`<p>Total: ${money(rows.reduce((s,r)=>s.plus(r.amount),D(0)))}. Remainder kobo are distributed by fractional share, with house number breaking ties.</p>`+(state.recorder?'<button type="button" class="primary" id="post-generator">Record this advance charge</button>':'');document.querySelector('#post-generator')?.addEventListener('click',async ev=>{ev.target.disabled=true;try{await api('entries',{id,kind:'generator-charge',amount:input.budget,...input,note:'Generator advance contribution'});await load();report('Generator advance charges recorded.');}catch(e){report(e.message);ev.target.disabled=false;}});}catch(e){report(e.message);}};}
function settlementForm(){
 const advances=state.entries.filter(e=>e.kind==='generator-charge'&&!state.entries.some(s=>s.advanceId===e.id));
 if(!advances.length){report('There are no unreconciled generator advances.');return;}
 const dialog=document.querySelector('#dialog');
 dialog.innerHTML=`<button id="close" class="secondary">Close</button><h2>Reconcile generator costs</h2><p>Confirm actual expenses against the recorded diesel and servicing entries, then enter final credited or approved estimated units. Negative differences become house credits; positive differences are additional amounts due. Cash receipts are already credited separately.</p><form id="settlement-form"><label>Recorded advance<select name="advanceId">${advances.map(e=>`<option value="${esc(e.id)}">${esc(e.date)} · ${money(e.amount)}</option>`).join('')}</select></label><label>Approved actual expense total (₦)<input name="amount" type="number" min="0" step="0.01" required></label><label>Reconciliation date<input type="date" name="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Expense references and reconciliation explanation<textarea name="note" required maxlength="500"></textarea></label><label>Final unmetered estimation basis<input name="basis" required maxlength="200"></label><div id="final-units"></div><button class="primary">Preview credits and shortfalls</button><div id="settlement-result" aria-live="polite"></div><p id="settlement-error" role="alert"></p></form>`;
 dialog.showModal();document.querySelector('#close').onclick=()=>dialog.close();
 const form=document.querySelector('#settlement-form');
 const units=()=>{const advance=advances.find(a=>a.id===form.elements.advanceId.value);document.querySelector('#final-units').innerHTML=advance.occupied.map(h=>`<label>House ${h} final units<input name="units${h}" type="number" min="0" step="0.000001" required></label>`).join('');};
 units();form.elements.advanceId.onchange=units;
 form.addEventListener('input',()=>document.querySelector('#settlement-result').replaceChildren());
 form.onsubmit=e=>{e.preventDefault();try{
   const fields=Object.fromEntries(new FormData(form)),advance=advances.find(a=>a.id===fields.advanceId),input={...fields,id:crypto.randomUUID(),kind:'generator-settlement',amount:D(fields.amount).toFixed(2),units:Object.fromEntries(advance.occupied.map(h=>[h,fields['units'+h]]))};
   const rows=generatorSettlement(advance,{budget:input.amount,units:input.units});
   document.querySelector('#settlement-result').innerHTML=table(['House','Original advance','Final charge','Additional charge / credit'],rows.map(r=>`<tr><td>House ${r.house}</td><td>${money(r.advance)}</td><td>${money(r.finalCharge)}</td><td>${money(r.amount)} ${D(r.amount).lt(0)?'credit':''}</td></tr>`))+'<p>This closes the selected advance once. Later corrections require a separate audited adjustment.</p><button type="button" class="primary" id="confirm-settlement">Confirm reconciliation</button>';
   document.querySelector('#confirm-settlement').onclick=async ev=>{ev.target.disabled=true;try{await api('entries',input);dialog.close();await load();report('Reconciliation recorded. House credits and shortfalls have been carried into current balances.');}catch(error){document.querySelector('#settlement-error').textContent=error.message;ev.target.disabled=false;}};
 }catch(error){document.querySelector('#settlement-error').textContent=error.message;}};
}
const toolLifecycle=new AbortController();
if(document.modelContext?.registerTool){
 try{Promise.resolve(document.modelContext.registerTool({name:'read_house_statement',description:'Read a house’s original monthly balances and its current balance after new ledger records.',inputSchema:{type:'object',properties:{house:{type:'integer',minimum:1,maximum:9}},required:['house'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!history||!state)throw Error('Records have not loaded.');if(!Number.isInteger(input?.house)||input.house<1||input.house>9)throw Error('House must be 1 to 9.');return {house:input.house,current:currentBalances(history,state.entries).find(r=>r.house===input.house),history:history.statements.filter(s=>s.house===input.house).map(s=>({period:s.period,closing:s.closing,occupancy:s.occupancy,source:s.fields.Outstanding.source}))};}},{signal:toolLifecycle.signal})).catch(()=>{});}catch{}
}
window.addEventListener('pagehide',()=>toolLifecycle.abort(),{once:true});
load();
